### ISSUE TITLE
httpretty (from moto) and tornado.testing are not friend

### ISSUE THREAD

**Issue by tarekziade** [loads/loads-broker#26]
Trying to test the web app by using AsyncHTTPTestCase, I ran into an issue where httpretty patches the socket module and that breaks tornado testing when it tries to bind a local socket on an unused port.

https://github.com/gabrielfalcao/HTTPretty/issues/247

I'll hack something around but httpretty need to get fixed

**Comment by chartjes** [comment]
wontfix
