### ISSUE TITLE
Add pagination to API

### ISSUE THREAD

**Issue by pdehaan** [loads/loads-broker#28]
... for Projects and stuff.

We currently have a https://github.com/loads/loads-web/issues/40 bug for pagination for the loads-web side, but need server support to only return 20+/- results at a time, instead of potentially downloading hundreds or millions of records at once.

**Comment by rpappalax** [comment]
We need our GET query to allow for  returning specific number of historical records
would require api to handle both start & limit parameters:
Example
https://loads-web.stage.mozaws.net:5000/api - home page (should return first 25 records)
click on >> Next link to view previous 25 records
query would be something like....
https://loads-web.stage.mozaws.net:5000/api?start=26&limit=25 
etc.
