### ISSUE TITLE
/api endpoint should track who initiated a load test

### ISSUE THREAD

**Issue by pdehaan** [loads/loads-broker#30]
... so we know whom to blame.

Related to #29, and this was something that was possible w/ Loads V1:

> "Test was launched by: rpappalardo"

---

Here's a crude snippet of the Loads V2 `/api` endpoint response:
```js
{  
  "status": 200,
  "version": "0.1",
  "success": true,
  "runs": [  
    {  
      "created_at": "2015-08-25T18:13:44.239076",
      "id": 1,
      "state": 3,
      "aborted": true,
      "uuid": "f934b3b2-0889-4a5b-8e45-0f65b3980ecb",
      "plan_id": 11,
      "started_at": "2015-08-25T18:21:34.516381",
      "completed_at": "2015-08-25T18:21:34.529243"
    },
    // ...
}
```
See https://github.com/loads/loads-web/pull/85 for example of current /api output.

If a load test is initiated via the loads v2 web app, maybe we can pass along the currently logged in user id. If a load test is initiated via the command line, maybe the user can specify their user id using the honor system (and maybe we refuse the load test request if a user id isn't specified).

**Comment by tarekziade** [comment]
I am adding a change so you can pass 'creator' to the /api/orchestrate endpoint. When you do it, the run will get an "owner" field that will be returned when calling /api
