### ISSUE TITLE
ProgrammingError: SQLite objects created in thread cannot be used in another thread.

### ISSUE THREAD

**Issue by Natim** [loads/loads-broker#31]
```sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140219959453504 and this is thread id 140219156240128```

**Comment by rpappalax** [comment]
started broker with --no-influx option and seeing same error

**Comment by tarekziade** [comment]
fixed with https://github.com/loads/loads-broker/commit/0301e9ac68d7095f532425eca6a657f0bd8439af
