### ISSUE TITLE
console entry point: loads run <plan id> doesn't work

### ISSUE THREAD

**Issue by rpappalax** [loads/loads-broker#38]
running
$ loads run <plan id>

returns:
loads: error: unrecognized arguments: <plan id>

however, curl -XPOST http://localhost:8080/api/orchestrate/<plan id>
works fine

**Comment by tarekziade** [comment]
You have to provide a strategy id to start a run

```sh
$ bin/loads run
{"message": "No such strategy.", "success": false, "status": 404}
```

```sh
$ bin/loads run --help
usage: loads run [-h] [--user-data USER_DATA] [--cset-name CSET_NAME]
                 [--image-name IMAGE_NAME] [--nodes NODES]
                 [--strategy-id STRATEGY_ID] [--image-url IMAGE_URL]

optional arguments:
  -h, --help            show this help message and exit
  --user-data USER_DATA
                        user-data
  --cset-name CSET_NAME
                        Name of container set
  --image-name IMAGE_NAME
                        Name of image to use
  --nodes NODES         Number of nodes to instanciate
  --strategy-id STRATEGY_ID
                        Strategy ID to use
  --image-url IMAGE_URL
                        URL of image to use
```

What would you like to see instead ?

**Comment by rpappalax** [comment]
@tarekziade yea, i'm aware but this involves some not-very-user-friendly copy/pasta.  ideally, the user would be able to select the strategy "description" or name directly from a menu (which is what we're implimenting via the loads-cli.   since we should be able to acomplish this from the REST API, we'll close this for now.
