### ISSUE TITLE
Add IP's to an instance to increase max outbound connections

### ISSUE THREAD

**Issue by bbangert** [loads/loads-broker#4]
Depending on how much CPU is needed on an instance, at some point it might be useful to use Elastic Network Interfaces to add more IP's to a single instance and bind a docker daemon to each one for additional load testing agents. This likely won't be needed for awhile, so recording this in a ticket for posterity.

**Comment by chartjes** [comment]
Closing due to staleness, please re-open if you'd like to see it addressed
