### ISSUE TITLE
locksmithd is restarting the new instances after 10 minutes

### ISSUE THREAD

**Issue by Natim** [loads/loads-broker#40]
While running loop loadtests, it seems that new instances get updated by coreos/locksmithd and then get restarted at some point while loadtest are running.

    Broadcast message from locksmithd at 2016-02-08 15:23:24.82201178 +0000 UTC:   
    System reboot in 5 minutes!

**Comment by Natim** [comment]
Broadcast message from locksmithd at 2016-02-12 10:00:56.980803078 +0000 UTC:  
System reboot in 5 minutes!

**Comment by tarekziade** [comment]
we should deactivate this and rebuild the AMI

e.g. https://coreos.com/os/docs/latest/update-strategies.html

**Comment by tarekziade** [comment]
we need to tweak the CoreOS via cloud-config to avoid this reboot, with the update option

```
coreos:
  update:
    reboot-strategy: off
```
in https://github.com/loads/loads-broker/blob/master/loadsbroker/webapp/aws.yml

That will let the broker create images that won't reboot

**Comment by rpappalax** [comment]
No longer seeing this issue. closing

**Comment by TimoDJatomika** [comment]
I still receive the issue using the iam `ami-879b946c` using no cloud-config.
