### ISSUE TITLE
Add swagger

### ISSUE THREAD

**Issue by rpappalax** [loads/loads-broker#82]
Since loads-broker will be a proper service, we should probably swaggerify this (same as any other services project)

**Comment by tarekziade** [comment]
Looks like most Tornado swagger extension are outdate or not python 3 compatible or very intrusive.

I am wondering how hard it would be to propose a simple generic tool that can be used to build the swagger file given a few descriptors here and there, independently from the framework.

Working on it now

**Comment by chartjes** [comment]
Not needed with plan to switch over to using ardere
